spring:
  application:
    name: baemin

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/delivery
    username: sparta
    password: sparta26

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

